framework:
    secret: '%env(APP_SECRET)%'
    session: true
    serializer:
        mapping:
            path:
                - '%kernel.project_dir%/config/api_platform/serialization'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file